apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName }}-job
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      restartPolicy: OnFailure 
