apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "maven-app.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "maven-app.name" . }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/sh"]
          args: ["-c", "java -jar myapp.jar && sleep infinity"]
          ports:
            - containerPort: {{ .Values.service.port }}
