name: myapp pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Read current version from pom.xml and increment the patch version
    - name: Increment patch version
      id: version
      run: |
        # Get the current version from the pom.xml
        cd myapp
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        NEW_VERSION=$(echo $VERSION | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.)        
        # Update pom.xml with the new version
        mvn versions:set -DnewVersion=$NEW_VERSION
        mvn clean install
        echo "new version: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" 

    - name: Commit and push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Bump version to ${{ steps.version.outputs.NEW_VERSION }}"
        git push
        
    - name: Compile Package and Create an artifact item
      run: |
        mvn clean package

